### ISSUE TITLE
Option to choose HD Model

### ISSUE THREAD

**Issue by LinqLover** [LinqLover/simple-openai-tts-playground#4]
As a user, I would like a simple option in the playground to choose a different model (such as the HD model) in the playground. Maybe a simple checkbox suffices. Maybe a drop-down is better?

**Comment by Hassaan68** [comment]
@LinqLover , can you please assign this one to me ?

**Comment by LinqLover** [comment]
@Hassaan68 Sure, done! Great to have you on board. Let me know if you need any help!

**Comment by Hassaan68** [comment]
Thanks @LinqLover , what options do you want in dropdown or what are the possible values for model? I am placing the dropdown after voice select dropdown and MODEL is passed as constant for now I will change it to variable.

**Comment by Hassaan68** [comment]
ok, so I got the list from here https://platform.openai.com/docs/models/tts.

**Comment by LinqLover** [comment]
The UI sounds good! Apparently there are currently just two models, tts-1 and tts-1-hd. See: https://platform.openai.com/docs/api-reference/audio/createSpeech

This is why I'd also considered using a checkbox instead but a drop-down has the advantage of being more generic and aligning closer to how programmers would use the API.
