### ISSUE TITLE
Storing the API keys 

### ISSUE THREAD

**Issue by Gitstar-OC** [LinqLover/simple-openai-tts-playground#6]
Hello LinqLover, I just visited this app and find out that there are security breaches, which means anyone with a good skill can see what someone has done before, so I guess you should work on this site's security more than the main thing, I loved that you have written the code in such a way which does not store anything, but if you want to scale this up you would like to use a database so the user don't need to enter his api key again and again, this might fix some security errors. By which platform are you hosting this site?

**Comment by LinqLover** [comment]
Hi @Gitstar-OC, thanks for your issue. What security breaches are you referring to? This is a small client-side app without a server in the background. TTS requests are sent to the OpenAI API directly from the browser. The last API key and all generated audio samples are stored in the browser's local storage so you don't have to enter your key again every time or spend unnecessary money on the API. The app is hosted on GitHub Pages.

**Comment by Gitstar-OC** [comment]
I thought off that you are not taking any type of storage in use, that's why I opened the issue. Having API key stored in browser local storage is good. Thanks for informing me. I have added this project in my contribution list once my React App is complete (within 3 - 4 days) I would like to collaborate with you currently closing this issue.

**Comment by LinqLover** [comment]
Sounds good! Looking forward to any contributions! :-)
